config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  controller :home do
    get :about
    get :dashboard
    get :seed
  end

  resources :lists, except: [:index] do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  controller :users do
    get :signup, action: :new, as: :signup
    post :signup, action: :create

    get :settings, action: :edit
    patch :settings, action: :update

    get "settings/change-password", action: :change_password
    patch "settings/change-password", action: :update_password
  end

  controller :sessions do
    get :login, action: :new, as: :login
    post :login, action: :create
    get :logout, action: :destroy, as: :logout
  end

  get '@:username', to: 'users#show', as: :profile, username: /[^\/]+/
  get "/:username", to: redirect { |params, request| "/@#{params[:username]}" }
end

app/models/list.rb
class List < ActiveRecord::Base
  # 'public' and 'private' are reserved words
  enum status: [:publik, :secret, :priv8]

  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :items, inverse_of: :list, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_secure_token :secret_id

  has_permalink

  accepts_nested_attributes_for :items,
    reject_if: proc { |params| params['body'].blank? },
    allow_destroy: true

  validates :title, presence: true
  validates :user_id, presence: true

  validates_associated :items
  validates_associated :comments

  def secret_link
    (persisted? && secret?) ? "https://listyourlist.com/lists/#{secret_id}" : nil
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authorize, except: [:show]
  before_action :find_list, only: [:edit, :update, :destroy]

  def show
    secret_list = List.find_by(secret_id: params[:id])

    if secret_list
      @list = secret_list
      @title = "#{@list.title} / #{@list.user.username}"
      @comment = Comment.new
    else
      @list = List.find_by(permalink: params[:id])
      @comment = Comment.new

      if @list&.publik? || current_user.owns?(@list)
        @title = "#{@list.title} / #{@list.user.username}"
      else
        redirect_to root_path
      end
    end
  end

  def new
    @title = "New List"
    @list = current_user.lists.new
    @list.items.build
  end

  def create
    @title = "New List"
    @list = current_user.lists.new(list_params)

    if @list.items.present? && @list.save
      redirect_to dashboard_path, notice: "Your list was created! 🎉"
    else
      @list.errors.add(:items, "A list must have at least one item") if @list.items.empty?
      @list.items.build
      render :new
    end
  end

  def edit
    @title = @list.title
  end

  def update
    before = @list.status
    after = list_params[:status]

    if @list.update_attributes(list_params)
      process_secret_id(before, after)
      redirect_to dashboard_path, notice: "Your list was updated. 🛠"
    else
      render :edit
    end
  end

  def destroy
    if @list.destroy
      return redirect_to dashboard_path, notice: "Your list was deleted. 😥"
    else
      render :edit
    end
  end

  private

  def find_list
    @list = List.find_by!(user: current_user, permalink: params[:id])
  end

  def process_secret_id(before, after)
    if before != "secret" && after == "secret"
      @list.regenerate_secret_id
    end

    if before == "secret" && after != "secret"
      @list.update_attribute(:secret_id, nil)
    end
  end

  def list_params
    params.require(:list).permit(
      :user_id,
      :title,
      :description,
      :ordered,
      :commenting,
      :status,
      items_attributes: [:id, :body, :position, :_destroy]
    )
  end
end

app/helpers/lists_helper.rb
module ListsHelper
  def link_to_user(user)
    link_to user.username, profile_path(user.username)
  end

  def editable_by_current_user?(list, current_user)
    current_user.lists.include?(list) if current_user
  end

  def listed_by(list, current_user)
    if editable_by_current_user?(@list, current_user)
      "Listed by <strong>YOU</strong> on #{@list.created_at.strftime("%B #{@list.created_at.day.ordinalize}, %Y")} :"
    else
      "Listed by #{link_to_user(@list.user)} on #{@list.created_at.strftime("%B #{@list.created_at.day.ordinalize}, %Y")}"
    end
  end
end

app/views/lists/_form.html.erb
<div class="col-sm-7">

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_area :title, class: "form-control input-lg flex-text" %>
    <%= error_messages_for(@list, :title, "right") %>
  </div>

  <div class="form-group">
    <%= f.label :description, "Description (optional)" %>
    <%= f.text_area :description, class: "form-control input-lg description flex-text" %>
  </div>

  <%= error_messages_for(@list, :items, "left") %>

  <div class="list">
    <<%= @list.ordered ? "o" : "u" %>l id="items">
      <%= f.fields_for :items do |item| %>
        <%= render 'item_fields', f: item %>
      <% end %>
      <div class="links" data-association-insertion-position="before" data-association-insertion-node="this">
        Type and hit ENTER, or <%= link_to_add_association "click here", f, :items %> <%= link_to "🤔", "#", class: "js-form-help form-help-link", style: "text-decoration: none" %>
      </div>
    </<%= @list.ordered ? "o" : "u" %>l>
  </div>

  <div class="form-help" style="display:none">
    <%= strikethrough_heading(text: "Lil Form Helper") %>

    <p>Navigating the list form ☝🏼 is really fun with a couple keyboard shortcuts. Well, it's actually only sorta one shortcut, but it's got lots of features! Once you get the hang of it, you'll be listing lists with maximum efficiency.</p>
    <h5>TL;DR 👉🏼 <strong>Hit ENTER</strong> 🤓</h5>
    <p>The best way to navigate between fields is by hitting ENTER:
    <ul>
      <li>Type your title, hit ENTER, and the cursor will move to Description.</li>
      <li>Type your Description, hit ENTER, and the cursor will move to the first Item.</li>
      <li>Type your Item, hit ENTER, a new item appears, and the cursor will move to it.</li>
      <li>And, if you hit ENTER in the last item field while it's empty, nothing happens!</li>
    </ul>
    <p>All of the above continues to work even after you've filled stuff out. So, let's say you need to edit the Title after creating a bunch items. Make your adjustments to the title and then just hit ENTER a bunch of times: the cursor will cruise right on through the Description and all existing items until it stops at the last empty item field.</p>
    <h5>What about tab?</h5>
    <p>You can still tab between fields like normal, and the cool part is that even after tabbing into a field and highlighting its contents, hitting ENTER still moves the cursor along to the next field.</p>
    <!-- TODO make this a link to our email address or contact form -->
    <p>Last but not least, if you've got feedback (good or bad), please send us an email.</p>
    <h5>And since you made it this far, you get a star! ⭐️</h5>
  </div>
</div>

<div class="settings col-sm-5">
  <div class="section">
    <%= strikethrough_heading(text: "List Type") %>

    <div class="options">
      <label>
        <%= f.radio_button :ordered, false, checked: true, class: "js-switch-list-type" %>
        <span>BULLETS</span>
      </label>
      <label>
        <%= f.radio_button :ordered, true, class: "js-switch-list-type" %>
        <span>NUMBERS</span>
      </label>
    </div>
  </div>

  <div class="section">
    <%= strikethrough_heading(text: "Comments") %>

    <div class="options">
      <label>
        <%= f.radio_button :commenting, true, checked: true %>
        <span>ON</span>
      </label>
      <label>
        <%= f.radio_button :commenting, false %>
        <span>OFF</span>
      </label>
    </div>
  </div>

  <div class="section status">
    <%= strikethrough_heading(text: "Status") %>

    <div class="options">
      <label class="status">
        <%= f.radio_button :status, "publik", checked: true, class: "js-switch-list-status"  %>
        <span>Public</span>
      </label>
      <label class="status">
        <%= f.radio_button :status, "secret", class: "js-switch-list-status"  %>
        <span>Secret</span>
      </label>
      <label class="status">
        <%= f.radio_button :status, "priv8", class: "js-switch-list-status"  %>
        <span>Private</span>
      </label>
    </div>

    <p class="status-help-text">
      <span class="status-help-text-publik" <%= display_if(@list.publik?) %>>
        Public lists are visible to everyone, even robots (search engines).
      </span>

      <span class="status-help-text-secret" <%= display_if(@list.secret?) %>>
        Secret lists are visible only with the link below. They are not searchable by people or robots, but anyone with the Secret Link can see your secret list.
      </span>

      <span class="status-help-text-priv8" <%= display_if(@list.priv8?) %>>
        Private lists are only visible to you (when you're logged in).
      </span>
    </p>
  </div>

  <div class="section secret-link" <%= display_if(@list.secret?) %>>
    <%= strikethrough_heading(text: "😶 Secret Link 😶") %>

    <%= text_field_tag "secret_link", @list.secret_link || "Check back here after you save 💃🏻", readonly: !@list.secret?, class: "form-control input-lg" %>

    <p class="secret-help-text" <%= display_if(@list.secret?) %>>
      Click the link to copy it
    </p>
  </div>

  <div class="section">
    <%= f.submit "SAVE LIST", class: "btn btn-lg btn-block btn-lyl-primary" %>
  </div>

  <% if action_name == "edit" %>
    <div class="section">
      <%= link_to "DELETE LIST", @list, method: :delete, class: "btn btn-lg btn-block btn-lyl-delete", data: { confirm: "Are you sure you wanna delete this list? It will be gone forever and you can't undo this." } %>
    </div>
  <% end %>
</div>

app/views/lists/_item_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <li>
      <%= f.hidden_field :position, value: f.index.to_i + 1, class: "js-list-item-position" %>

      <div class="form-group">
        <%= f.text_area :body, class: "form-control input-lg flex-text item js-list-item", placeholder: "List Item #{f.index.to_i + 1}" %>
      </div>

      <%= link_to_remove_association f, tabindex: -1, data: { confirm: "Are you sure you want to remove this list item?" } do %>
        <%= fa_icon "times-circle" %>
      <% end %>
    </li>
  </div>
</div>

app/views/lists/_lists.html.erb
<div class="row">
	<div class="col-sm-4 col-md-4 col-lg-4">
		<ul class="list-group">
      <li class="list-group-item justify-content-between header">
        NEW LISTS
      </li>
      <% lists_new.each do |list| %>
        <li class="list-group-item justify-content-between">
          <%= link_to list.title, list_path(list), class: "list" %>
        </li>
      <% end %>
		</ul>
	</div>
	<div class="col-sm-4 col-md-4 col-lg-4">
		<ul class="list-group">
      <li class="list-group-item justify-content-between header">
        RECENT ACTIVITY
      </li>
      <% lists_activity.each do |list| %>
        <li class="list-group-item justify-content-between">
          <%= link_to list.title, list_path(list), class: "list" %>
        </li>
      <% end %>
		</ul>
	</div>
	<div class="col-sm-4 col-md-4 col-lg-4">
		<ul class="list-group">
      <li class="list-group-item justify-content-between header">
        MOST POPULAR
      </li>
      <% lists_popular.each do |list| %>
        <li class="list-group-item justify-content-between">
          <%= link_to list.title, list_path(list), class: "list" %>
        </li>
      <% end %>
		</ul>
	</div>
</div>

app/views/lists/edit.html.erb
<div id="list-form">
  <%= form_for @list, html: { class: "js-list-form" } do |f| %>
    <h2>Editing Your List</h2>

    <div class="row">
      <%= render partial: "form", locals: { f: f } %>
    </div>
  <% end %>
</div>

app/views/lists/index.html.erb
<div id="lists">
  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th>All Lists</th>
        <th class="stat">User</th>
        <th class="stat">Comments</th>
        <th class="stat">Likes</th>
      </tr>
    </thead>
    <tbody>
      <% @lists.each do |list| %>
          <tr>
            <td><%= link_to list.title, list_path(list) %></td>
            <td class="stat"><%= link_to list.user.username, profile_path(list.user.username) %></td>
            <td class="stat"><%= list.comments.size %></td>
            <td class="stat"><%= list.likes.size %></td>
          </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/lists/new.html.erb
<div id="list-form">
  <%= form_for @list, html: { class: "js-list-form" } do |f| %>
    <h2>Create a new list</h2>

    <div class="row">
      <%= render partial: "form", locals: { f: f } %>
    </div>
  <% end %>
</div>

app/views/lists/show.html.erb
<div id="list">
  <div class="row">
    <div class="col-sm-7">
      <% if current_user && current_user.owns?(@list) && (@list.secret? || @list.priv8?) %>
        <div class="secret-or-private">
          <% if @list.secret? %>
            <h4>This is a secret list! It is only visible to you, and anyone that you share your Secret Link with:</h4>
            <p><%= link_to @list.secret_link, @list.secret_link %></p>
          <% end %>

          <% if @list.priv8? %>
            <h4>This is your private list. It is only visible to you.</h4>
          <% end %>
        </div>
      <% end %>

      <h2><%= @list.title %></h2>
      <%= simple_format(@list.description, class: "description") %>

      <!-- TODO make block helper for this ? -->
      <<%= @list.ordered ? "o" : "u" %>l class="single_list">
        <% @list.items.each do |item| %>
          <li><%= item.body %></li>
        <% end %>
      </<%= @list.ordered ? "o" : "u" %>l>

      <!-- TODO make block helper for this ? -->
      <p class="listed_by">
        <% if editable_by_current_user?(@list, current_user) %>
          <% if @list.priv8? %>
            Privately listed
          <% else %>
            Listed
          <% end %>
          by <strong><%= link_to "YOU", profile_path(current_user.username) %></strong> on <%= @list.created_at.strftime("%B #{@list.created_at.day.ordinalize}, %Y") %> : <%= link_to "EDIT", edit_list_path(@list) %>
        <% else %>
          Listed by <%= link_to_user(@list.user) %> on <%= @list.created_at.strftime("%B #{@list.created_at.day.ordinalize}, %Y") %>
        <% end %>
      </p>

      <% if @list.commenting? %>
        <% if @list.comments.present? %>

          <%= strikethrough_heading(text: "COMMENTS") %>

          <ul class="comments">
            <% @list.comments.each do |comment| %>
              <li id="comment_<%= comment.id %>">
                <span class="comment">
                  <%= simple_format(comment.body) %>
                </span>

                <!-- TODO make block helper for this ? -->
                <p class="commented_by">
                  posted by <%= link_to comment.user.username, profile_path(comment.user.username) %>

                  <% if comment.more_than_one_week_old? %>
                    on <%= comment.created_at.strftime("%B #{comment.created_at.day.ordinalize}, %Y") %>
                  <% else %>
                    <%= time_ago_in_words(comment.created_at) %> ago
                  <% end %>

                  <% if current_user && current_user == comment.user  %>
                    | <%= link_to list_comment_path(@list, comment), method: :delete, data: { confirm: "Are you sure you want to delete this comment?" } do %>
                      <%= fa_icon "trash-o" %>
                    <% end %>
                  <% end %>
                </p>
              </li>
            <% end %>
          </ul>
        <% end %>

        <%= strikethrough_heading(text: @list.comments.present? ? "ADD A NEW COMMENT" : "BE THE FIRST TO COMMENT") %>

        <%= form_for [@list, @comment] do |f| %>
          <%= f.text_area :body, class: "form-control input-lg comment-textarea" %>
          <p class="comment-help-text">
            <em>There is only one of you. There is no "internet self" and "real self." If you're not kind on the internet, then you're not kind.</em> -
            <a href="https://twitter.com/glennondoyle/status/522526229761904640" class="mellow" target="_blank">Glennon Doyle</a>
          </p>
          <%= f.submit "SAVE COMMENT", class: "btn btn-lg btn-block btn-lyl-primary" %>
        <% end %>
      <% end %>
    </div>

    <div class="col-sm-5">
      <ul class="list-group">
        <li class="list-group-item justify-content-between header">
          <%= @list.user.username %>
        </li>
        <% @list.user.lists.publik.reverse.each do |list| %>
          <li class="list-group-item justify-content-between">
            <%= link_to_unless_current list.title, list_path(list), class: "list" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>