config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  controller :home do
    get :about
    get :dashboard
    get :seed
  end

  resources :lists, except: [:index] do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  controller :users do
    get :signup, action: :new, as: :signup
    post :signup, action: :create

    get :settings, action: :edit
    patch :settings, action: :update

    get "settings/change-password", action: :change_password
    patch "settings/change-password", action: :update_password
  end

  controller :sessions do
    get :login, action: :new, as: :login
    post :login, action: :create
    get :logout, action: :destroy, as: :logout
  end

  get '@:username', to: 'users#show', as: :profile, username: /[^\/]+/
  get "/:username", to: redirect { |params, request| "/@#{params[:username]}" }
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token

  has_many :lists, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_secure_password

  validates :username,
    presence: true,
    format: {
      with: /\A[\w\.]+\z/,
      message: "only allows letters, numbers, underscores, and periods"
    }

  validates :email,
    presence: true,
    format: { with: /[\S]+\@[\S]+\.[\S]+/ }

  validates :url,
    format: {
      with: /\A(http|https):\/\/[\S]+\.[\S]+\z/,
      message: "is invalid. Make sure you include 'http://' or 'https://' at the beginning.",
      allow_blank: true
    }

  validates_associated :lists
  validates_associated :comments

  def owns?(list)
    list.in?(lists)
  end

  ### AUTHENTICATION STUFF, KEEP AT BOTTOM ###

  class << self
    def new_token
      SecureRandom.urlsafe_base64
    end

    def digest(string)
      cost = if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end

      BCrypt::Password.create(string, cost: cost)
    end
  end

  def remember!
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget!
    update_attribute(:remember_digest, nil)
  end

  def authenticated?(remember_token)
    if remember_digest && remember_token
      BCrypt::Password.new(remember_digest).is_password?(remember_token)
    else
      return false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, :find_user,
    only: [:edit, :update, :change_password, :update_password]

  def show
    @user = User.find_by(username: params[:username])

    if @user
      @title = @user.username
    else
      redirect_to root_path
    end
  end

  def new
    redirect_to dashboard_path if current_user

    @title = "Sign Up"
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to dashboard_path
    else
      @title = "Sign Up"
      render :new
    end
  end

  def edit
    @title = "Edit your account"
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to dashboard_path, notice: "Your account info was updated. 👍🏼"
    else
      @title = "Edit your account"
      render :edit, alert: "Your account info did not save. 🤔 See below for details."
    end
  end

  def change_password
    @title = "Change Password"
  end

  def update_password
    @title = "Change Password"

    if @user.authenticate(user_params[:current_password])
      @user.password = user_params[:password]
      @user.password_confirmation = user_params[:password_confirmation]

      if @user.save
        redirect_to settings_path, notice: "Your password was changed. 👍🏼"
      else
        render :change_password, alert: "Something's not right here... 🤔"
      end
    else
      @user.errors.add(:current_password, "was not correct")
      render :change_password, alert: "Something's not right here... 🤔"
    end
  end

  private

  def find_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(
      :username,
      :email,
      :full_name,
      :location,
      :url,
      :bio,
      :password,
      :password_confirmation,
      :current_password
    )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="section required">
  <%= strikethrough_heading(text: "REQUIRED") %>

  <div class="form-group">
    <%= f.label :username, "Username" %>
    <%= f.text_field :username, class: "form-control input-lg", placeholder: "Letters, numbers, dashes, and dots" %>
    <%= error_messages_for(@user, :username) %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control input-lg", placeholder: "example@poopypants.net" %>
    <%= error_messages_for(@user, :email) %>
  </div>

  <% if action_name == "new" || action_name == "create" %>
    <div class="form-group">
      <%= f.label :password, "Passwords" %>
      <%= f.password_field :password, class: "form-control input-lg", placeholder: "Password" %>
      <%= error_messages_for(@user, :password) %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation, class: "sr-only" %>
      <%= f.password_field :password_confirmation, class: "form-control input-lg", placeholder: "Confirm Password" %>
      <%= error_messages_for(@user, :password_confirmation) %>
    </div>
  <% else %>
    <p class="text-center">
      <%= link_to "Click here to change your password", settings_change_password_path %>
    </p>
  <% end %>
</div>

<div class="section optional">
  <%= strikethrough_heading(text: "OPTIONAL") %>

  <div class="form-group">
    <%= f.label :full_name, "Full Name" %>
    <%= f.text_field :full_name, class: "form-control input-lg", placeholder: "First and last" %>
  </div>

  <div class="form-group">
    <%= f.label :location %>
    <%= f.text_field :location, class: "form-control input-lg", placeholder: "City, State, Country?" %>
  </div>

  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url, class: "form-control input-lg", placeholder: "https://example.com" %>
    <%= error_messages_for(@user, :url) %>
  </div>

  <div class="form-group">
    <%= f.label :bio %>
    <%= f.text_area :bio, class: "form-control input-lg", placeholder: "What's your story?" %>
  </div>
</div>

app/views/users/change_password.html.erb
<div id="change-password">
  <h2 class="text-center">Change your password</h2>
  <%= form_for @user, url: { action: :change_password } do |f| %>

    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <%= strikethrough_heading(text: "CURRENT PASSWORD") %>

        <div class="form-group">
          <%= f.label :current_password, class: "sr-only" %>
          <%= f.password_field :current_password, class: "form-control input-lg", placeholder: "Can you remember it?" %>
          <%= error_messages_for(@user, :current_password) %>
        </div>

        <%= strikethrough_heading(text: "NEW PASSWORD") %>

        <div class="form-group">
          <%= f.label :password, class: "sr-only" %>
          <%= f.password_field :password, class: "form-control input-lg", placeholder: "New Password" %>
          <%= error_messages_for(@user, :password) %>
        </div>

        <div class="form-group">
          <%= f.label :password_confirmation, class: "sr-only" %>
          <%= f.password_field :password_confirmation, class: "form-control input-lg", placeholder: "Confirm New Password" %>
          <%= error_messages_for(@user, :password_confirmation) %>
        </div>

        <div class="actions">
          <%= f.submit "UPDATE PASSWORD", class: "btn btn-lg btn-block btn-lyl-primary" %>
        </div>
      </div>
    </div>

  <% end %>
</div>

app/views/users/edit.html.erb
<div id="users-form">
  <h2 class="text-center">Edit your account info</h2>
  <%= form_for @user, url: { action: :edit } do |f| %>

    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <%= render partial: "form", locals: { f: f } %>

        <div class="actions">
          <%= f.submit "UPDATE ACCOUNT INFO", class: "btn btn-lg btn-block btn-lyl-primary" %>
        </div>
      </div>
    </div>

  <% end %>
</div>

app/views/users/new.html.erb
<div id="users-form">
  <h2 class="text-center">Create your account</h2>
  <%= form_for @user, url: { action: :create } do |f| %>

    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <%= render partial: "form", locals: { f: f } %>

        <div class="actions">
          <%= f.submit "Save", class: "btn btn-lg btn-block btn-lyl-primary" %>
        </div>
      </div>
    </div>

  <% end %>
</div>

app/views/users/seed.html.erb
# USERS<br/>
[<br />
<% @users.each do |user| %>
&nbsp;&nbsp;{ id:  <%= user.id %>, login: "<%= user.login %>", email: "<%= user.email %>", location: "<%= user.location %>", url: "<%= user.url %>", bio: "<%= user.bio %>", full_name: "<%= user.full_name %>", display_name: "<%= user.display_name %>", deleted: <%= user.deleted %> },<br />
<% end %>
].each do |user|<br />
&nbsp;&nbsp;User.create!(user)<br />
end<br />
<br />
# LISTS<br/>
[<br />
<% @lists.each do |list| %>
&nbsp;&nbsp;{ id: <%= list.id %>, user_id: <%= list.user_id %>, title: %^<%= list.title %>^, description: %^<%= list.description %>^, published: <%= list.published %>, ordered: <%= list.ordered %>, hits: <%= list.hits %>, created_at: "<%= list.created_at %>", updated_at: "<%= list.updated_at %>", deleted: <%= list.deleted %> },<br />
<% end %>
].each do |list|<br />
&nbsp;&nbsp;List.create!(list)<br />
end<br />
<br />
# ITEMS<br/>
[<br />
<% @items.each do |item| %>
&nbsp;&nbsp;{ id: <%= item.id %>, list_id: <%= item.list_id %>, body: %^<%= item.body %>^, position: <%= item.position %> },<br />
<% end %>
].each do |item|<br />
&nbsp;&nbsp;Item.create!(item)<br />
end<br />
<br />
# COMMENTS<br/>
[<br />
<% @comments.each do |comment| %>
&nbsp;&nbsp;{ id: <%= comment.id %>, user_id: <%= comment.user_id %>, list_id: <%= comment.list_id %>, body: %^<%= comment.body %>^, created_at: "<%= comment.created_at %>", deleted: <%= comment.deleted %> },<br />
<% end %>
].each do |item|<br />
&nbsp;&nbsp;Comment.create!(item)<br />
end<br />
<br />
# LIKES<br/>
[<br />
<% @likes.each do |like| %>
&nbsp;&nbsp;{ id: <%= like.id %>, user_id: <%= like.user_id %>, list_id: <%= like.list_id %>, created_at: "<%= like.created_at %>" },<br />
<% end %>
].each do |like|<br />
&nbsp;&nbsp;Like.create!(like)<br />
end<br />

app/views/users/show.html.erb
<div id="user">
  <div class="row">
    <div class="col-sm-6">
      <ul class="list-unstyled">
        <li><%= @user.full_name ? @user.full_name : @user.username %></li>
        <li><%= @user.location %></li>
        <li><%= link_to @user.url, @user.url, target: "_blank" if @user.url %></li>
        <li><%= @user.bio %></li>
      </ul>
    </div>
    <div class="col-sm-6">
      <ul class="list-group">
        <li class="list-group-item justify-content-between header">
          Lists
        </li>
        <% @user.lists.publik.order(created_at: :desc).each do |list| %>
          <li class="list-group-item justify-content-between">
            <%= link_to list.title, list_path(list), class: "list" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>