config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  controller :home do
    get :about
    get :dashboard
    get :seed
  end

  resources :lists, except: [:index] do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  controller :users do
    get :signup, action: :new, as: :signup
    post :signup, action: :create

    get :settings, action: :edit
    patch :settings, action: :update

    get "settings/change-password", action: :change_password
    patch "settings/change-password", action: :update_password
  end

  controller :sessions do
    get :login, action: :new, as: :login
    post :login, action: :create
    get :logout, action: :destroy, as: :logout
  end

  get '@:username', to: 'users#show', as: :profile, username: /[^\/]+/
  get "/:username", to: redirect { |params, request| "/@#{params[:username]}" }
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authorize, only: [:dashboard, :seed]

  def index
    @title = "Pointless List-Making at its Finest"
    @lists_new = List.publik.order(created_at: :desc).limit(14)
    @lists_activity = List.publik.where(id: Comment.order(created_at: :desc).limit(14).map(&:list_id).uniq)
    @lists_popular = List.publik.order(hits: :desc).limit(14)
  end

  def about
    @title = "About"
  end

  def dashboard
    @title = "Dashboard / Admin"
    @publik_lists = current_user.lists.publik.order(created_at: :desc)
    @secret_lists = current_user.lists.secret.order(created_at: :desc)
    @priv8_lists = current_user.lists.priv8.order(created_at: :desc)
  end

  def seed
    if current_user.username == "eliduke"
      @users    = User.unscoped.order(:id)
      @lists    = List.unscoped.order(:id)
      @items    = Item.unscoped.order(:id)
      @comments = Comment.unscoped.order(:id)
      @likes    = Like.unscoped.order(:id)

      render layout: false
    else
      redirect_to dashboard_path
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div id="about">
	<h3>About</h3>

	<h5>A little back story&hellip;</h5>
	<p>This whole thing started back in the Spring of 2006. I realized pretty quickly that if I was <em>really</em> going to learn <%= link_to "Ruby on Rails", "http://rubyonrails.com" %>, I needed something more than "the depot." I tossed a few ideas around in my head and settled on <em>List<span>Y</span>ourList</em>.</p>
	<p>Sure, there were 100 other list sites out there, but I thought I had something original enough. With the help of my good friend (and fellow nerd), Shane, we whipped out the first version of <em>List<span>Y</span>ourList</em> and launched it on <%= link_to "my sister", "/worstdukeever" %>'s birthday: May 23rd, 2006.</p>
	<p class="last_p">Things went pretty well. After only a few weeks we had about 50 listers listing away! It was awesome. Each and everyday I was excited to see what new lists had been listed. The creativity and humor of the community was very surprising, and I was extremely proud of everyone involved.</p>

	<h5>Then what happened?</h5>
	<p>Well, I got a little burnt out on the whole "web design" thing. See, I'd created a few custom-made blogs for my friends and I was dealing with hosting and bug tracking for those, I was fresh off some frustrating contract work, Rails hosting and deployment were an f-ing nightmare, and I had a sinking suspicion that I was spending <em>way</em> too much time on the computer.</p>
	<p>So, I walked away from the whole thing and took a small hiatus. I migrated all my friends' blogs to wordpress.com and took down <em>ListYourList</em>. I was done. I tried giving the project away on craigslist, but all of the prospective takers flaked out on me.</p>

	<blockquote>
		<h5>FREE Rails project for passionate programmer</h5>
		<p>Are you new to Ruby on Rails, but just can't find the right project with which to get your hands dirty? Are you a master chef just yearning for another pot to stir? Have I got the deal for you.</p>
		<p>I used to be a RoR programmer, and then I fell out of the game.</p>
		<p>I created a project, launched it, got about 50 users and lots of activity, and then lost my passion. Unfortunately in this case, the ship sorta went down with the captain and the traffic tanked. I hate seeing it sitting around collecting dust and would love to pass it off to someone more passionate and excited to continue the legacy. And the best part is, you can have it completely free!!</p>
		<p>Send me an email, I'll send you the URL, and you can poke around and get back to me. Or, maybe we could meet up, I could show you what I've got, and then hand you the reins. What do you say?</p>
  </blockquote>

	<p>About a year later (Jan 2008), while <%= link_to "washing dishes in Antarctica", "http://flickr.com/photos/elisfanclub/collections/72157602618746680/" %>, I got an email from a friend of <%= link_to "Rosa", "/rosa" %>. She whipped me into shape.</p>

	<blockquote>
		<h5>Dear Eli</h5>
		<p>I was just procrastinating online, and I was distressed to find that listyourlist.com seems to have died a death.  My good friend Rosa sent me a link to this blog, and I saw that you have disengaged yourself from it entirely.</p>
		<p>When I first discovered the absence of listyourlist, I looked for a substitute (aided by Rosa).  It appears that listyourlist was unique in the un-gimmicky function it offered to people, and in the way that lists were completely independent, and attached to the user only.</p>
	</blockquote>

	<p>When I got back home in June, I reunited with Shane, and we rebuilt <em>ListYourList</em> from the ground up. It was an awesome exercise in redesign and refactoring.</p>

  <h5>Fast-Forward Seven Years</h5>

  <p>It's now 2015, and I am rebuilding <em>ListYourList</em> once again! It's has remained practically dormant over the last 7 years, and in that time a lot has changed in the world of the web. The previous version of <em>ListYourList</em> was zero percent mobile friendly, and that has become completely unacceptable these days. It was also in dire need of a redesign. It's also my baby and babies need babying every so often.</p>

  <p>For now, though, the site is read-only while I get the back-end all tied together. Take a moment to read through your old lists or discover some new ones. A lot of them still hold up. If for any reason you don't want your lists, comments, or your entire account on the site anymore, send me an email and I'll delete it for you. Eventually you will have that power, but until then, there is another option.</p>

	<p>Questions? Comments? Feedback? <%= link_to "Contact me", "mailto:elimduke@gmail.com" %>.</p>
</div>

app/views/home/dashboard.html.erb
<div id="dashboard">
  <% if current_user.lists.empty? %>
    <div class="row">
      <div class="col-sm-12 welcome">
        <h1>Oh, heeeeeey!</h1>
        <h2>Welcome to ListYourList. We are so happy to have you. 🤗</h2>
        <p>You're about to get started listing your first list, but before that, a couple small things to address.</p>
        <p>First and foremost, this is purely a for-funzies kind of website. Please have fun and encourage others to do the same.</p>
        <p>Secondly, we want this thing to be the best that it can be. If you've got feedback (good or bad), please send us an email.</p>
        <p>Lastly, don't forget to get creative and think outside the checkbox!</p>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="col-sm-6">
      <%= link_to new_list_path, class: "btn btn-lg btn-block btn-lyl-default create-list" do %>
        ⭐️ CREATE NEW LIST ⭐️
      <% end %>

      <ul class="list-group">
        <li class="list-group-item justify-content-between header">
          YOUR PUBLIC LISTS (<%= @publik_lists.size %>)
        </li>
        <% if @publik_lists.present? %>
          <% @publik_lists.each do |list| %>
            <li class="list-group-item justify-content-between">
              <span class="badge badge-pill badge-default">
                <%= link_to edit_list_path(list) do %>
                  <%= fa_icon "edit" %>
                <% end %>
              </span>
              <%= link_to list.title, list_path(list), class: "list" %>
            </li>
          <% end %>
        <% else %>
          <li class="list-group-item justify-content-between">
            You have no public lists yet.
          </li>
        <% end %>
      </ul>
    </div>

    <div class="col-sm-6">
      <ul class="list-group">
        <li class="list-group-item justify-content-between header">
          YOUR SECRET LISTS (<%= @secret_lists.size %>)
        </li>
        <% if @secret_lists.present? %>
          <% @secret_lists.each do |list| %>
            <li class="list-group-item justify-content-between">
              <span class="badge badge-pill badge-default">
                <%= link_to edit_list_path(list) do %>
                  <%= fa_icon "edit" %>
                <% end %>
              </span>
              <%= link_to list.title, list_path(list), class: "list" %>
            </li>
          <% end %>
        <% else %>
          <li class="list-group-item justify-content-between">
            You have no secret lists yet.
          </li>
        <% end %>
      </ul>

      <ul class="list-group">
        <li class="list-group-item justify-content-between header">
          YOUR PRIVATE LISTS (<%= @priv8_lists.size %>)
        </li>
        <% if @priv8_lists.present? %>
          <% @priv8_lists.each do |list| %>
            <li class="list-group-item justify-content-between">
              <span class="badge badge-pill badge-default">
                <%= link_to edit_list_path(list) do %>
                  <%= fa_icon "edit" %>
                <% end %>
              </span>
              <%= link_to list.title, list_path(list), class: "list" %>
            </li>
          <% end %>
        <% else %>
          <li class="list-group-item justify-content-between">
            You have no private lists yet.
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<% content_for :hero do %>
  <div id="home">
    <div class="container splash-container">
      <div class="row">
        <div class="col-sm-12 splash">
          <h1 class="text-center">Pointless List-Making at its Finest</h1>
          <p class="lead text-center">Think outside the checkbox and <b>get creative</b></p>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div id="home">
  <%= render partial: "lists/lists", locals: { lists_new: @lists_new, lists_activity: @lists_activity, lists_popular: @lists_popular } %>
</div>

app/views/home/seed.html.erb
# USERS<br/>
[<br />
<% @users.each do |user| %>
&nbsp;&nbsp;{ id:  <%= user.id %>, username: "<%= user.username %>", email: "<%= user.email %>", location: "<%= user.location %>", url: "<%= user.url %>", bio: "<%= user.bio %>", full_name: "<%= user.full_name %>" },<br />
<% end %>
].each do |user|<br />
&nbsp;&nbsp;User.create!(user)<br />
end<br />
<br />
# LISTS<br/>
[<br />
<% @lists.each do |list| %>
&nbsp;&nbsp;{ id: <%= list.id %>, user_id: <%= list.user_id %>, title: %^<%= list.title %>^, description: %^<%= list.description %>^, status: <%= list.status %>, ordered: <%= list.ordered %>, hits: <%= list.hits %>, created_at: "<%= list.created_at %>", updated_at: "<%= list.updated_at %>" },<br />
<% end %>
].each do |list|<br />
&nbsp;&nbsp;List.create!(list)<br />
end<br />
<br />
# ITEMS<br/>
[<br />
<% @items.each do |item| %>
&nbsp;&nbsp;{ id: <%= item.id %>, list_id: <%= item.list_id %>, body: %^<%= item.body %>^, position: <%= item.position %> },<br />
<% end %>
].each do |item|<br />
&nbsp;&nbsp;Item.create!(item)<br />
end<br />
<br />
# COMMENTS<br/>
[<br />
<% @comments.each do |comment| %>
&nbsp;&nbsp;{ id: <%= comment.id %>, user_id: <%= comment.user_id %>, list_id: <%= comment.list_id %>, body: %^<%= comment.body %>^, created_at: "<%= comment.created_at %>" },<br />
<% end %>
].each do |item|<br />
&nbsp;&nbsp;Comment.create!(item)<br />
end<br />
<br />
# LIKES<br/>
[<br />
<% @likes.each do |like| %>
&nbsp;&nbsp;{ id: <%= like.id %>, user_id: <%= like.user_id %>, list_id: <%= like.list_id %>, created_at: "<%= like.created_at %>" },<br />
<% end %>
].each do |like|<br />
&nbsp;&nbsp;Like.create!(like)<br />
end<br />