config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  controller :home do
    get :about
    get :dashboard
    get :seed
  end

  resources :lists, except: [:index] do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  controller :users do
    get :signup, action: :new, as: :signup
    post :signup, action: :create

    get :settings, action: :edit
    patch :settings, action: :update

    get "settings/change-password", action: :change_password
    patch "settings/change-password", action: :update_password
  end

  controller :sessions do
    get :login, action: :new, as: :login
    post :login, action: :create
    get :logout, action: :destroy, as: :logout
  end

  get '@:username', to: 'users#show', as: :profile, username: /[^\/]+/
  get "/:username", to: redirect { |params, request| "/@#{params[:username]}" }
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="<%= @list ? "List: #{@list.title}" : @title %>">
    <meta name="author" content="<%= @list.user if @list %>">

    <title><%= @title %> / ListYourList</title>

    <!-- http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css -->

    <link rel="stylesheet" href="/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-44211034-6', 'auto');
      ga('send', 'pageview');
    </script>

    <!-- Bootstrap core CSS -->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="../../assets/js/html5shiv.js"></script>
      <script src="../../assets/js/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="container">
      <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
          <div class="row">
            <div class="col-sm-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<%= root_path %>">List<span class="y">Y</span>ourList</a>
              </div>
              <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                  <% if current_user %>
                    <li><%= link_to "New List", new_list_path %></li>
                    <li><%= link_to "Dashboard", dashboard_path %></li>
                    <li><%= link_to "Settings", settings_path %></li>
                    <li><%= link_to "Logout", logout_path %></li>
                  <% else %>
                    <li><%= link_to "Login", login_path %></li>
                    <li><%= link_to "Sign Up", signup_path %></li>
                  <% end %>
                </ul>
              </div><!-- nav collapse -->
            </div>
          </div><!-- nav -->
        </div>
      </div>
    </div>

    <%= content_for :hero %>

    <div class="container">

      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <% if notice %>
            <div class="alert alert-lyl-success alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <strong>Success!</strong> <%= notice %>
            </div>
          <% end %>

          <% if alert %>
            <div class="alert alert-lyl-alert alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <strong>Oops!</strong> <%= alert %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-12 col-md-10 col-md-offset-1">
          <%= yield %>
        </div>
      </div>

    </div>
    <div id="footer">
      <div class="container footer-container">
        <p class="created_by">Created by <a href="http://eliduke.com" target="_blank">Eli Duke</a></p>
      </div>
    </div>
  </body>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>

</html>